name: Publicar Datapack Automatizado

on:
  workflow_dispatch: # <-- Esto habilita el botón manual en GitHub
  push:
    branches:
      - releases # Se activa automáticamente al hacer push o merge a 'releases'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Crear archivo .ZIP del Datapack
        run: |
          # Empaqueta la carpeta data, pack.mcmeta e imagen ignorando carpetas de Git
          zip -r datapack_casual.zip data pack.mcmeta pack.png -x "*.git*" "*.github*"

      - name: Publicar en CurseForge y Modrinth
        uses: Kir-Antipov/mc-publish@v3
        with:
          # Claves secretas de GitHub
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # IDs de tus proyectos
          curseforge-id: '1651937'
          modrinth-id: 'everyday-wear'

          # Configuración del archivo
          files: 'datapack_casual.zip' # <-- CORREGIDO: Ahora coincide exactamente con el nombre de arriba
          version: '1.0.0'
          version-type: 'release' # Puede ser: release, beta, alpha

          # Compatibilidad
          game-versions: '26.2'
          loaders: 'datapack'
