name: Publicar Datapack Automatizado
on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Número de versión del Datapack (ej. 1.1)'
        required: true
        default: '1.1'
      game_version_select:
        description: 'Versión objetivo de Minecraft'
        type: choice
        required: true
        default: '26.2'
        options:
          - '26.2'
          - '26.1'
          - '26.0'
      changelog:
        description: 'Notas de la versión (Changelog)'
        required: true
        default: 'Corrección de errores y mejoras generales.'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Crear archivo .ZIP del Datapack
        run: |
          VERSION="${{ github.event.inputs.version_number }}"
          zip -r "olddays-newways-${VERSION}.zip" data pack.mcmeta pack.png -x "*.git*" "*.github*"

      - name: Publicar en CurseForge y Modrinth
        uses: Kir-Antipov/mc-publish@v3
        with:
          # Claves secretas de GitHub
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          
          # IDs de tus proyectos
          curseforge-id: '1651937'
          modrinth-id: 'olddays-newways'
          
          # Archivos y versiones del datapack
          files: "olddays-newways-${{ github.event.inputs.version_number }}.zip"
          version: "${{ github.event.inputs.version_number }}"
          version-type: 'release' 
          
          # Changelog dinámico integrado
          changelog: "${{ github.event.inputs.changelog }}"
          
          # NUEVO: Selector dinámico que respeta la versión elegida (por defecto 26.2)
          game-versions: "${{ github.event.inputs.game_version_select }}"
          loaders: 'datapack'
